### ISSUE TITLE
Use "contrast" colors instead of "spectrum" colors

### ISSUE THREAD

**Issue by ukanuk** [pigoz/anki-canvas#8]
Thank you for this amazing function!!! I've gotten a vastly different card setup and typically write on pen/paper, but have added your drawing canvas to my card and love it when I'm on public transit and it's too shaky to use pen/paper!

One slight issue though, I've set up my diagrams to use the "contrast" coloring rather than "spectrum" coloring (`Tools` > `Add-ons` > `Kanji Colorizer stroke order diagrams` > `Config` and replace `"mode": "spectrum",` with `"mode": "contrast",`.

Can you implement similar functionality?

Or if you don't have time, could you point me at the parts of the javascript actually picking the colors for each stroke? I've done some C and python coding in my time, but am pretty unfamiliar with javascript and would have trouble going through your stuff from scratch. But if you pointed me to the relevant sections of code, maybe I could hack something together that works. 

If you're curious, this is what my cards look like:

*Front*
![image](https://user-images.githubusercontent.com/59303202/71558270-9c0f5b80-2a94-11ea-89ce-91bb972fe899.png)

*Rear*
![image](https://user-images.githubusercontent.com/59303202/71558271-a03b7900-2a94-11ea-9af5-c4f95f06ca7c.png)

**Comment by pigoz** [comment]
Hi! Glad you find the project useful. ✨ I use it on public transit too: on my phone using a stylus.

I've just made a [new release (v0.6)](https://github.com/pigoz/anki-canvas/releases/tag/v0.6) which allows you to choose the colorizer. More info on the [README](https://github.com/pigoz/anki-canvas#options).

Please reopen the issue if you have issues setting it up, or it doesn't work as expected.

**Comment by ukanuk** [comment]
I don't believe I have the ability to re-open this issue. Unfortunately when I imported your latest deck.apkg, it's not working as expected. First, the back card preview doesn't work at all (though it does work on the actual card, so maybe this is some unfortunate workaround?). Second, I changed the colorizer to `'contrast'` but it's still using spectrum coloring. 

Thank you for the quick response! 

![image](https://user-images.githubusercontent.com/59303202/71564592-a8bc9f80-2ae6-11ea-87db-9b1124cec62f.png)

**Comment by pigoz** [comment]
Whoops, that was a nasty bug. 🐛 
Should be fixed in https://github.com/pigoz/anki-canvas/releases/tag/v0.7

Please let me know if it works for you!

**Comment by ukanuk** [comment]
The back card preview still doesn't work at all in 0.7, despite having worked in version 0.5.

But, I tested the actual card and that seems to work both with front and rear of card, at least in light mode. I'll test dark mode later, but I assume that doesn't make any difference. 

0.7 card preview
![image](https://user-images.githubusercontent.com/59303202/71603998-e41ca400-2ba2-11ea-8988-522dd5eefc32.png)

0.5 card preview
![image](https://user-images.githubusercontent.com/59303202/71603979-d0713d80-2ba2-11ea-9916-343aa8aae2a4.png)

**Comment by pigoz** [comment]
I've fixed the card preview in 0.8! Thank you for all the testing & feedback.

**Comment by ukanuk** [comment]
All seems to be working well in my tests, thank you for this!!!
